//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import Quick
import Nimble
@testable import ___PROJECTNAME___Staging

class ___VARIABLE_sceneName___WorkerTests: QuickSpec {

    override func spec() {
        describe("___VARIABLE_sceneName___ Worker") {
            var worker: ___VARIABLE_sceneName___Worker!

            beforeEach {
                worker = ___VARIABLE_sceneName___Worker()
            }
        }
    }

}
